CREATE TABLE IF NOT EXISTS masters
(
   id    BIGSERIAL PRIMARY KEY ,
   player_id  BIGSERIAL ,
   login VARCHAR(20) NOT NULL ,
   password VARCHAR(20)  NOT NULL
);
CREATE TABLE IF NOT EXISTS players
(
   id    BIGSERIAL PRIMARY KEY ,
   login VARCHAR(20) NOT NULL ,
   password VARCHAR(20)  NOT NULL
);