DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
create TABLE IF NOT EXISTS master
(
    master_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login character varying(200) NOT NULL,
    password character varying(200) NOT NULL,
    CONSTRAINT constraint_master UNIQUE (login, password)
);

create TABLE IF NOT EXISTS player
(
    player_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login character varying(200) NOT NULL,
    password character varying(200) NOT NULL,
    CONSTRAINT constraint_player UNIQUE (login, password)
);

create TABLE IF NOT EXISTS wallet
(
    wallet_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crons integer NOT NULL,
    password character varying(200) NOT NULL
);

create TABLE IF NOT EXISTS items
(
    items_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weight integer NOT NULL
);

create TABLE IF NOT EXISTS item
(
    item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    items_id bigint  REFERENCES items(items_id),
    name character varying(200) NOT NULL,
    weight integer NOT NULL,
    value integer NOT NULL,
    pickup_date character varying(200) NOT NULL
);

create TABLE IF NOT EXISTS inventory
(
    inventory_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id bigint REFERENCES wallet(wallet_id),
    items_id bigint REFERENCES items(items_id)
);

create TABLE IF NOT EXISTS start_characteristics
(
    start_characteristics_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement integer NOT NULL,
    weaponSkill integer NOT NULL,
    ballisticSkill integer NOT NULL,
    strength integer NOT NULL,
    toughness integer NOT NULL,
    initiative integer NOT NULL,
    dexterity integer NOT NULL,
    leadership integer NOT NULL,
    intelligence integer NOT NULL,
    willPower integer NOT NULL,
    fellowship integer NOT NULL
);

create TABLE IF NOT EXISTS characteristics
(
    characteristics_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement integer NOT NULL,
    weaponSkill integer NOT NULL,
    ballisticSkill integer NOT NULL,
    strength integer NOT NULL,
    toughness integer NOT NULL,
    initiative integer NOT NULL,
    dexterity integer NOT NULL,
    leadership integer NOT NULL,
    intelligence integer NOT NULL,
    willPower integer NOT NULL,
    fellowship integer NOT NULL
);

create TABLE IF NOT EXISTS resilience
(
    resilience_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resilience text NOT NULL,
    resolve text NOT NULL,
    motivation text NOT NULL
);

create TABLE IF NOT EXISTS ambitions
(
    ambitions_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_ambitions text NOT NULL,
    long_ambitions text NOT NULL
);

create TABLE IF NOT EXISTS description
(
    description_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resilience_id bigint REFERENCES resilience(resilience_id),
    ambitions_id bigint REFERENCES ambitions(ambitions_id),
    description text NOT NULL
);

create TABLE IF NOT EXISTS experience
(
    experience_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    current_exp integer NOT NULL,
    spent_exp integer NOT NULL,
    total_exp integer NOT NULL
);
create TABLE IF NOT EXISTS fate
(
    fate_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fate integer NOT NULL,
    fortune integer NOT NULL
);
create TABLE IF NOT EXISTS basic_skills
(
    basic_skills_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    art integer NOT NULL,
    athletics  integer NOT NULL,
    bribery  integer NOT NULL,
    charm  integer NOT NULL,
    charmAnimal  integer NOT NULL,
    climb  integer NOT NULL,
    cool  integer NOT NULL,
    consumeAlcohol  integer NOT NULL,
    dodge  integer NOT NULL,
    drive  integer NOT NULL,
    endurance  integer NOT NULL,
    entertain  integer NOT NULL,
    gamble  integer NOT NULL,
    gossip  integer NOT NULL,
    haggle  integer NOT NULL,
    intimidate  integer NOT NULL,
    intuition  integer NOT NULL,
    leadership  integer NOT NULL,
    melle  integer NOT NULL,
    navigation  integer NOT NULL,
    outDoorSurvival  integer NOT NULL,
    perception  integer NOT NULL,
    ride  integer NOT NULL,
    row  integer NOT NULL,
    stealth  integer NOT NULL
);
create TABLE IF NOT EXISTS start_basic_skills
(
    start_basic_skills_id bigint PRIMARY KEY,
    art integer NOT NULL,
    athletics  integer NOT NULL,
    bribery  integer NOT NULL,
    charm  integer NOT NULL,
    charmAnimal  integer NOT NULL,
    climb  integer NOT NULL,
    cool  integer NOT NULL,
    consumeAlcohol  integer NOT NULL,
    dodge  integer NOT NULL,
    drive  integer NOT NULL,
    endurance  integer NOT NULL,
    entertain  integer NOT NULL,
    gamble  integer NOT NULL,
    gossip  integer NOT NULL,
    haggle  integer NOT NULL,
    intimidate  integer NOT NULL,
    intuition  integer NOT NULL,
    leadership  integer NOT NULL,
    melle  integer NOT NULL,
    navigation  integer NOT NULL,
    outDoorSurvival  integer NOT NULL,
    perception  integer NOT NULL,
    ride  integer NOT NULL,
    row  integer NOT NULL,
    stealth  integer NOT NULL
);

create TABLE IF NOT EXISTS playable_сharacter
(
    playable_сharacter_id bigint PRIMARY KEY,
    name character varying(200) NOT NULL,
    player_id bigint REFERENCES player(player_id),
    master_id bigint REFERENCES master(master_id),
    inventory_id bigint REFERENCES inventory(inventory_id),
    start_characteristics_id bigint REFERENCES start_characteristics(start_characteristics_id),
    characteristics_id bigint REFERENCES characteristics(characteristics_id),
    description_id bigint REFERENCES description(description_id),
    basic_skills_id bigint REFERENCES basic_skills(basic_skills_id),
    start_basic_skills_id bigint REFERENCES start_basic_skills(start_basic_skills_id),
    fate_id bigint REFERENCES fate(fate_id)
);